### ISSUE TITLE
First argument must be an abstract-leveldown compliant store

### ISSUE THREAD

**Issue by parweb** [jed/sheet-down#8]
I try to run the homepage example with those version
```
  "dependencies": {
    "google-oauth-jwt-stream": "^1.0.4",
    "levelup": "^3.1.1",
    "sheet-down": "^1.1.3"
  }
```

But i have this error

```
node index.js

/web/sheet-down/example/node_modules/levelup/lib/levelup.js:49
    throw error
    ^
InitializationError: First argument must be an abstract-leveldown compliant store
    at new LevelUP (/web/sheet-down/example/node_modules/levelup/lib/levelup.js:45:13)
    at LevelUP (/web/sheet-down/example/node_modules/levelup/lib/levelup.js:29:12)
    at Object.<anonymous> (/web/sheet-down/example/index.js:12:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
```

**Comment by parweb** [comment]
I succeed by changing the version of levelup
```
 "dependencies": {
    "google-oauth-jwt-stream": "^1.0.4",
    "levelup": "^0.19.0",
    "sheet-down": "^1.1.3"
  }
```
